[package]
name = "solar-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8.1"
linux-embedded-hal = "0.3.2"
ssd1306 = "0.8.4"
